# Site settings
title: Sarah Kirk
email: 
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site for Sarah Kirk
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://kharsikar.github.io" # the base hostname & protocol for your site
twitter_username: Kharsikar
github_username:  Kharsikar

# Build settings
markdown: kramdown
